"""Rename base model

Revision ID: 791b782df62a
Revises: 942e778cfe1e
Create Date: 2023-12-27 00:44:11.934139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '791b782df62a'
down_revision = '942e778cfe1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
