"""full_amount > 0

Revision ID: be4f85218371
Revises: 791b782df62a
Create Date: 2023-12-27 00:47:55.621380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be4f85218371'
down_revision = '791b782df62a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
